### ISSUE TITLE
Steam report - advanced options turning to black screen

### ISSUE THREAD

**Issue by Condy-jpg** [College-Kings/College-Kings#200] opened 2022-04-14 23:21 UTC
The advance page on path builder seems to be glitched for me. I can select addition details of my choices from CK1 but theirs no confirm button so I click return and the screen goes black. Step 5 is blank nothing to select, I tried the advance button at each step lets me click the boxes but always goes black screen after hitting return button and have to close the game.

**Comment by Condy-jpg** [comment] 2022-04-15 00:15
Heard that pressing ESC helps

**Comment by KiloOscarSix** [comment] 2022-04-15 17:31
duplicate of #197

**Closed by KiloOscarSix** 2022-04-15 17:31 UTC
Labels: duplicate, platform: ck2
